### ISSUE TITLE
Error on load from different screen

### ISSUE THREAD

**Issue by justinenerio** [fluttercommunity/page_turn#2]
#### Issue description

Error when calling from screen during Navigator.push

#### Console log

```
E/flutter ( 8171): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: NoSuchMethodError: The method 'toImage' was called on null.
E/flutter ( 8171): Receiver: null
E/flutter ( 8171): Tried calling: toImage()
E/flutter ( 8171): #0      RenderRepaintBoundary.toImage (package:flutter/src/rendering/proxy_box.dart:2901)
E/flutter ( 8171): #1      _PageTurnWidgetState._captureImage (package:page_turn/src/builders/widget.dart:40)
E/flutter ( 8171): #2      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1102)
E/flutter ( 8171): #3      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1049)
E/flutter ( 8171): #4      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:957)
E/flutter ( 8171): #5      _rootRun (dart:async/zone.dart:1126)
E/flutter ( 8171): #6      _CustomZone.run (dart:async/zone.dart:1023)
E/flutter ( 8171): #7      _CustomZone.runGuarded (dart:async/zone.dart:925)
E/flutter ( 8171): #8      _invoke (dart:ui/hooks.dart:259)
E/flutter ( 8171): #9      _drawFrame (dart:ui/hooks.dart:217)
```

**Comment by josenelsoncultri** [comment]
Can you send me the part of your code that you're doing it? It's interesting to me...
